# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZ4Q_6RvYLl_efqWSB1qq0FB8iSLPVhJ
"""

import sys
sys.setrecursionlimit(10000)  # Allow deeper recursion for large numbers


def factorial(n):
    """
    Compute factorial using recursion.

    Recursive definition:
    factorial(n) = 1 if n = 0 or n = 1
    factorial(n) = n * factorial(n-1) if n > 1

    Args:
        n (int): Non-negative integer

    Returns:
        int: Factorial of n

    Raises:
        ValueError: If n is negative
        RecursionError: If recursion depth exceeds limit
    """
    # Base case: factorial of 0 or 1 is 1
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")

    if n == 0 or n == 1:
        return 1

    # Recursive case
    return n * factorial(n - 1)


def factorial_with_trace(n, depth=0):
    """
    Compute factorial with visual trace of recursive calls.
    Shows the call stack and return values.

    Args:
        n (int): Non-negative integer
        depth (int): Current recursion depth (for indentation)

    Returns:
        int: Factorial of n
    """
    indent = "  " * depth

    print(f"{indent}factorial({n}) called")

    # Base case
    if n == 0 or n == 1:
        print(f"{indent}Base case: factorial({n}) = 1")
        print(f"{indent}Returning 1")
        return 1

    # Recursive case
    print(f"{indent}Need to compute {n} * factorial({n-1})")
    result = n * factorial_with_trace(n - 1, depth + 1)
    print(f"{indent}Returning {n}! = {result}")

    return result


def factorial_iterative(n):
    """
    Compute factorial iteratively for comparison.

    Args:
        n (int): Non-negative integer

    Returns:
        int: Factorial of n
    """
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")

    result = 1
    for i in range(1, n + 1):
        result *= i
    return result


def factorial_memoized(n, memo={}):
    """
    Compute factorial using memoization (dynamic programming).
    Stores previously computed results for efficiency.

    Args:
        n (int): Non-negative integer
        memo (dict): Cache of computed factorials

    Returns:
        int: Factorial of n
    """
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")

    if n == 0 or n == 1:
        return 1

    if n not in memo:
        memo[n] = n * factorial_memoized(n - 1, memo)

    return memo[n]


def get_user_input():
    """
    Get valid input from the user.

    Returns:
        int: Valid non-negative integer entered by user
    """
    while True:
        try:
            user_input = input("\nEnter a non-negative integer (or 'quit' to exit): ").strip()

            if user_input.lower() in ['quit', 'q', 'exit']:
                return None

            num = int(user_input)

            if num < 0:
                print("Error: Please enter a non-negative integer (0 or greater)")
                continue

            if num > 20:
                print("Warning: Factorials larger than 20! will be very large numbers")
                confirm = input("Continue? (y/n): ").strip().lower()
                if confirm != 'y':
                    continue

            return num

        except ValueError:
            print("Error: Invalid input. Please enter an integer or 'quit'")
        except KeyboardInterrupt:
            print("\n")
            return None


def demonstrate_factorials():
    """
    Demonstrate factorial calculations with various methods.
    """
    print("\n" + "="*60)
    print("FACTORIAL CALCULATOR - RECURSION DEMONSTRATION")
    print("="*60)
    print()

    # Demonstrate with sample values
    sample_values = [21, 62, 92, 20]

    print("SAMPLE CALCULATIONS")
    print("-"*40)
    for n in sample_values:
        result = factorial(n)
        print(f"{n:2}! = {result:,}")

    print("\n" + "-"*40)
    print("RECURSIVE TRACE FOR 5!")
    print("-"*40)
    factorial_with_trace(5)

    print("\n" + "-"*40)
    print("COMPARISON OF METHODS")
    print("-"*40)
    n = 10
    rec_result = factorial(n)
    iter_result = factorial_iterative(n)
    mem_result = factorial_memoized(n)

    print(f"Recursive:    {n}! = {rec_result:,}")
    print(f"Iterative:    {n}! = {iter_result:,}")
    print(f"Memoized:     {n}! = {mem_result:,}")

    return n


def main():
    """
    Main interactive program for factorial calculation.
    """
    print("\n" + "="*60)
    print("RECURSIVE FACTORIAL CALCULATOR")
    print("="*60)
    print("This program demonstrates recursion by calculating factorials")
    print("Factorial definition: n! = n × (n-1) × ... × 1")
    print("Recursive formula: n! = n × (n-1)!, with 0! = 1")
    print()

    # Show demonstration
    demonstrate_factorials()

    print("\n" + "="*60)
    print("INTERACTIVE MODE")
    print("="*60)

    # Interactive mode
    while True:
        num = get_user_input()

        if num is None:
            print("\nExiting program. Goodbye!")
            break

        try:
            print("\n" + "-"*40)
            print(f"CALCULATING {num}!")
            print("-"*40)

            # Show method selection
            print("\nSelect calculation method:")
            print("1. Recursive (with trace)")
            print("2. Recursive (standard)")
            print("3. Iterative")
            print("4. Memoized")

            method = input("Enter choice (1-4, default=1): ").strip() or "1"

            print()

            if method == "1":
                # Recursive with trace
                result = factorial_with_trace(num)
                print(f"\nFinal Result: {num}! = {result:,}")

            elif method == "2":
                # Standard recursive
                result = factorial(num)
                print(f"Standard recursive: {num}! = {result:,}")

            elif method == "3":
                # Iterative
                result = factorial_iterative(num)
                print(f"Iterative: {num}! = {result:,}")

            elif method == "4":
                # Memoized
                result = factorial_memoized(num)
                print(f"Memoized: {num}! = {result:,}")

            else:
                print("Invalid method, using standard recursive")
                result = factorial(num)
                print(f"{num}! = {result:,}")

            # Show additional information
            print(f"\nNumber of digits: {len(str(result))}")

        except ValueError as e:
            print(f"Error: {e}")
        except RecursionError:
            print("Error: Number too large for recursion depth limit.")
            print("Try using iterative method for large numbers.")


if __name__ == "__main__":
    main()