# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pznhtaoznxrwegs3gL6-tvcoDf2MmodP
"""

class StudentNode:
    """
    Node class for Binary Search Tree.
    Each node contains student registration number and name.
    """

    def __init__(self, reg_no, name):
        """
        Initialize a student node.

        Args:
            reg_no (int): Student registration number (key)
            name (str): Student name (value)
        """
        self.reg_no = reg_no
        self.name = name
        self.left = None
        self.right = None


class BinarySearchTree:
    """
    Binary Search Tree class for managing student records.
    Students are organized by registration number.
    """

    def __init__(self):
        """Initialize an empty BST."""
        self.root = None
        self.num_nodes = 0

    def insert(self, reg_no, name):
        """
        Insert a student record into the BST.
        If registration number exists, update the name.

        Args:
            reg_no (int): Student registration number
            name (str): Student name
        """
        if self.root is None:
            self.root = StudentNode(reg_no, name)
            self.num_nodes += 1
            print(f"[Inserted] {reg_no}: {name} (as root)")
        else:
            self._insert_recursive(self.root, reg_no, name)

    def _insert_recursive(self, node, reg_no, name):
        """
        Recursive helper function for insertion.

        Args:
            node (StudentNode): Current node being examined
            reg_no (int): Registration number to insert
            name (str): Student name
        """
        if reg_no < node.reg_no:
            if node.left is None:
                node.left = StudentNode(reg_no, name)
                self.num_nodes += 1
                print(f"[Inserted] {reg_no}: {name} (left child of {node.reg_no})")
            else:
                self._insert_recursive(node.left, reg_no, name)
        elif reg_no > node.reg_no:
            if node.right is None:
                node.right = StudentNode(reg_no, name)
                self.num_nodes += 1
                print(f"[Inserted] {reg_no}: {name} (right child of {node.reg_no})")
            else:
                self._insert_recursive(node.right, reg_no, name)
        else:
            # Update existing record
            old_name = node.name
            node.name = name
            print(f"[Updated] {reg_no}: {old_name} -> {name}")

    def search(self, reg_no):
        """
        Search for a student by registration number.

        Args:
            reg_no (int): Registration number to search for

        Returns:
            tuple: (reg_no, name) if found, None otherwise
        """
        return self._search_recursive(self.root, reg_no)

    def _search_recursive(self, node, reg_no):
        """
        Recursive helper function for search.

        Args:
            node (StudentNode): Current node being examined
            reg_no (int): Registration number to search for

        Returns:
            tuple: (reg_no, name) if found, None otherwise
        """
        if node is None:
            return None

        if reg_no == node.reg_no:
            return (node.reg_no, node.name)
        elif reg_no < node.reg_no:
            return self._search_recursive(node.left, reg_no)
        else:
            return self._search_recursive(node.right, reg_no)

    def search_by_name(self, name):
        """
        Search for students by name (case-insensitive).

        Args:
            name (str): Name to search for

        Returns:
            list: List of (reg_no, name) tuples matching the search
        """
        results = []
        self._search_by_name_recursive(self.root, name.lower(), results)
        return results

    def _search_by_name_recursive(self, node, name_lower, results):
        """
        Recursive helper for name-based search.
        """
        if node is None:
            return

        # Check current node
        if node.name.lower() == name_lower:
            results.append((node.reg_no, node.name))

        # Search left and right subtrees
        self._search_by_name_recursive(node.left, name_lower, results)
        self._search_by_name_recursive(node.right, name_lower, results)

    def inorder_traversal(self):
        """
        Perform in-order traversal and display all students.
        This displays students in ascending order by registration number.
        """
        if self.root is None:
            print("\nTree is empty")
            return

        print("\n" + "="*60)
        print("IN-ORDER TRAVERSAL (Sorted by Registration Number)")
        print("="*60)
        self._inorder_recursive(self.root)
        print(f"\nTotal students: {self.num_nodes}")

    def _inorder_recursive(self, node):
        """
        Recursive helper for in-order traversal.
        """
        if node:
            self._inorder_recursive(node.left)
            print(f"Reg No: {node.reg_no:6d} | Name: {node.name}")
            self._inorder_recursive(node.right)

    def preorder_traversal(self):
        """
        Perform pre-order traversal (Root, Left, Right).
        """
        if self.root is None:
            print("\nTree is empty")
            return

        print("\n" + "="*60)
        print("PRE-ORDER TRAVERSAL (Root, Left, Right)")
        print("="*60)
        self._preorder_recursive(self.root)

    def _preorder_recursive(self, node):
        """
        Recursive helper for pre-order traversal.
        """
        if node:
            print(f"Reg No: {node.reg_no:6d} | Name: {node.name}")
            self._preorder_recursive(node.left)
            self._preorder_recursive(node.right)

    def postorder_traversal(self):
        """
        Perform post-order traversal (Left, Right, Root).
        """
        if self.root is None:
            print("\nTree is empty")
            return

        print("\n" + "="*60)
        print("POST-ORDER TRAVERSAL (Left, Right, Root)")
        print("="*60)
        self._postorder_recursive(self.root)

    def _postorder_recursive(self, node):
        """
        Recursive helper for post-order traversal.
        """
        if node:
            self._postorder_recursive(node.left)
            self._postorder_recursive(node.right)
            print(f"Reg No: {node.reg_no:6d} | Name: {node.name}")

    def find_min(self):
        """
        Find the minimum registration number in the tree.

        Returns:
            tuple: (reg_no, name) of the minimum node
        """
        if self.root is None:
            return None

        current = self.root
        while current.left:
            current = current.left
        return (current.reg_no, current.name)

    def find_max(self):
        """
        Find the maximum registration number in the tree.

        Returns:
            tuple: (reg_no, name) of the maximum node
        """
        if self.root is None:
            return None

        current = self.root
        while current.right:
            current = current.right
        return (current.reg_no, current.name)

    def get_height(self):
        """
        Calculate the height of the tree.

        Returns:
            int: Height of the tree
        """
        return self._get_height_recursive(self.root)

    def _get_height_recursive(self, node):
        """
        Recursive helper for height calculation.
        """
        if node is None:
            return -1

        left_height = self._get_height_recursive(node.left)
        right_height = self._get_height_recursive(node.right)

        return max(left_height, right_height) + 1


def main():
    """
    Main function to demonstrate BST operations.
    Provides an interactive menu for user interaction.
    """
    print("\n" + "="*60)
    print("BINARY SEARCH TREE IMPLEMENTATION - STUDENT MANAGEMENT")
    print("="*60)
    print("Students organized by registration number")
    print()

    # Create BST and populate with sample data
    bst = BinarySearchTree()

    sample_data = [
        (113, "Waringa"),
        (112, "Grace "),
        (108, " Clark medina"),
        (121, "soraya myth"),
        (127, "kiruja ruth"),
        (133, "Karen "),

    ]

    print("Inserting sample records...")
    for reg_no, name in sample_data:
        bst.insert(reg_no, name)

    bst.inorder_traversal()
    print(f"\nTree height: {bst.get_height()}")
    print(f"Minimum registration number: {bst.find_min()}")
    print(f"Maximum registration number: {bst.find_max()}")

    # Interactive menu
    while True:
        print("\n" + "-"*40)
        print("BST OPERATIONS MENU")
        print("-"*40)
        print("1. Insert student record")
        print("2. Search by registration number")
        print("3. Search by student name")
        print("4. Display in-order traversal")
        print("5. Display pre-order traversal")
        print("6. Display post-order traversal")
        print("7. Show tree statistics")
        print("8. Exit")

        try:
            choice = input("\nEnter your choice (1-8): ").strip()

            if choice == '1':
                reg_no = int(input("Enter registration number: "))
                name = input("Enter student name: ")
                bst.insert(reg_no, name)
                bst.inorder_traversal()

            elif choice == '2':
                reg_no = int(input("Enter registration number to search: "))
                result = bst.search(reg_no)
                if result:
                    reg, name = result
                    print(f"\nStudent found: Reg No: {reg}, Name: {name}")
                else:
                    print(f"\nStudent with registration number {reg_no} not found")

            elif choice == '3':
                name = input("Enter student name to search: ")
                results = bst.search_by_name(name)
                if results:
                    print(f"\nFound {len(results)} student(s):")
                    for reg, stu_name in results:
                        print(f"  Reg No: {reg}, Name: {stu_name}")
                else:
                    print(f"\nNo student found with name '{name}'")

            elif choice == '4':
                bst.inorder_traversal()

            elif choice == '5':
                bst.preorder_traversal()

            elif choice == '6':
                bst.postorder_traversal()

            elif choice == '7':
                print(f"\nTree Statistics:")
                print(f"  Total nodes: {bst.num_nodes}")
                print(f"  Height: {bst.get_height()}")
                print(f"  Minimum: {bst.find_min()}")
                print(f"  Maximum: {bst.find_max()}")

            elif choice == '8':
                print("\nExiting program. Goodbye!")
                break

            else:
                print("\nInvalid choice. Please enter a number between 1 and 8.")

        except ValueError:
            print("\nInvalid input. Please enter numeric values for registration numbers.")
        except KeyboardInterrupt:
            print("\n\nProgram interrupted by user. Exiting...")
            break


if __name__ == "__main__":
    main()