# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SgsiHzCBOVQPenz51fSbL54mfLA5qQJp
"""

class HashTable:
    """
    Hash Table class using separate chaining for collision resolution.
    Each bucket contains a list of (key, value) pairs.
    """

    def __init__(self, size=10):
        """
        Initialize the hash table with a specified size.

        Args:
            size (int): Number of buckets in the hash table
        """
        self.size = size
        self.table = [[] for _ in range(size)]
        self.num_elements = 0

    def _hash(self, key):
        """
        Hash function that maps a registration number to an index.
        Uses modulo operation for distribution.

        Args:
            key (int): Registration number

        Returns:
            int: Index in the hash table
        """
        return key % self.size

    def insert(self, reg_no, name):
        """
        Insert or update a student record in the hash table.

        Args:
            reg_no (int): Student registration number (key)
            name (str): Student name (value)
        """
        index = self._hash(reg_no)

        # Check if the registration number already exists
        for i, (existing_reg, existing_name) in enumerate(self.table[index]):
            if existing_reg == reg_no:
                # Update existing record
                self.table[index][i] = (reg_no, name)
                print(f"[Updated] {reg_no}: {name}")
                return

        # Insert new record
        self.table[index].append((reg_no, name))
        self.num_elements += 1
        print(f"[Inserted] {reg_no}: {name}")

        # Check load factor and resize if necessary
        if self.num_elements / self.size > 0.75:
            self._resize()

    def search(self, reg_no):
        """
        Search for a student by registration number.

        Args:
            reg_no (int): Registration number to search for

        Returns:
            str: Student name if found, None otherwise
        """
        index = self._hash(reg_no)

        for reg, name in self.table[index]:
            if reg == reg_no:
                return name
        return None

    def delete(self, reg_no):
        """
        Delete a student record from the hash table.

        Args:
            reg_no (int): Registration number to delete

        Returns:
            bool: True if deleted, False if not found
        """
        index = self._hash(reg_no)

        for i, (reg, name) in enumerate(self.table[index]):
            if reg == reg_no:
                del self.table[index][i]
                self.num_elements -= 1
                print(f"[Deleted] {reg_no}: {name}")
                return True

        print(f"[Not Found] Registration number {reg_no}")
        return False

    def _resize(self):
        """
        Resize the hash table when load factor exceeds 0.75.
        Doubles the size and rehashes all elements.
        """
        old_table = self.table
        self.size *= 2
        self.table = [[] for _ in range(self.size)]
        self.num_elements = 0

        # Rehash all existing elements
        for bucket in old_table:
            for reg_no, name in bucket:
                self.insert(reg_no, name)

        print(f"[Resized] Hash table size doubled to {self.size}")

    def display(self):
        """
        Display all contents of the hash table.
        Shows each bucket and its contents.
        """
        print("\n" + "="*60)
        print("HASH TABLE CONTENTS")
        print("="*60)

        if self.num_elements == 0:
            print("Hash table is empty")
            return

        for i, bucket in enumerate(self.table):
            if bucket:
                print(f"\nBucket {i}:")
                for reg_no, name in bucket:
                    print(f"  -> Reg No: {reg_no}, Name: {name}")
            else:
                print(f"\nBucket {i}: [Empty]")

        print(f"\nTotal elements: {self.num_elements}")
        print(f"Load factor: {self.num_elements}/{self.size} = {self.num_elements/self.size:.2f}")

    def get_all_students(self):
        """
        Get all students in the hash table.

        Returns:
            list: List of (reg_no, name) tuples
        """
        students = []
        for bucket in self.table:
            students.extend(bucket)
        return sorted(students, key=lambda x: x[0])


def main():
    """
    Main function to demonstrate hash table operations.
    Provides an interactive menu for user interaction.
    """
    print("\n" + "="*60)
    print("HASH TABLE IMPLEMENTATION - STUDENT MANAGEMENT SYSTEM")
    print("="*60)
    print("Using chaining for collision handling")
    print()

    # Create hash table with initial size 5 to demonstrate collisions
    ht = HashTable(size=5)

    # Pre-populate with some sample data
    sample_data = [
        (105, "Patricia "),
        (106, "inga"),
        (107, "Glory"),
        (104, "David "),
        (109, "stephanise"),  # Will collide with 101 if size=5 (101%5=1, 106%5=1)
        (110, "justus"),
        (111, "esther"),    # May cause resizing
    ]

    print("Inserting sample records...")
    for reg_no, name in sample_data:
        ht.insert(reg_no, name)

    ht.display()

    # Interactive menu
    while True:
        print("\n" + "-"*40)
        print("HASH TABLE OPERATIONS MENU")
        print("-"*40)
        print("1. Insert student record")
        print("2. Search for student")
        print("3. Delete student record")
        print("4. Display all records")
        print("5. Exit")

        try:
            choice = input("\nEnter your choice (1-5): ").strip()

            if choice == '1':
                reg_no = int(input("Enter registration number: "))
                name = input("Enter student name: ")
                ht.insert(reg_no, name)
                ht.display()

            elif choice == '2':
                reg_no = int(input("Enter registration number to search: "))
                result = ht.search(reg_no)
                if result:
                    print(f"\nStudent found: Reg No: {reg_no}, Name: {result}")
                else:
                    print(f"\nStudent with registration number {reg_no} not found")

            elif choice == '3':
                reg_no = int(input("Enter registration number to delete: "))
                ht.delete(reg_no)
                ht.display()

            elif choice == '4':
                ht.display()

            elif choice == '5':
                print("\nExiting program. Goodbye!")
                break

            else:
                print("\nInvalid choice. Please enter a number between 1 and 5.")

        except ValueError:
            print("\nInvalid input. Please enter numeric values for registration numbers.")
        except KeyboardInterrupt:
            print("\n\nProgram interrupted by user. Exiting...")
            break


if __name__ == "__main__":
    main()