# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkuV3DdU-V7P7RZke94n0SjIo8C4ndMn
"""

class Graph:

    def __init__(self):
        """Initialize an empty graph."""
        self.adjacency_list = {}
        self.num_vertices = 0
        self.num_edges = 0

    def add_vertex(self, vertex):
        """
        Add a vertex to the graph.

        Args:
            vertex: Vertex to add (can be string, integer, etc.)

        Returns:
            bool: True if added, False if already exists
        """
        if vertex not in self.adjacency_list:
            self.adjacency_list[vertex] = []
            self.num_vertices += 1
            print(f"[Added Vertex] {vertex}")
            return True
        else:
            print(f"[Warning] Vertex {vertex} already exists")
            return False

    def add_edge(self, vertex1, vertex2):
        """
        Add an edge between two vertices.
        Creates vertices if they don't exist.

        Args:
            vertex1: First vertex
            vertex2: Second vertex

        Returns:
            bool: True if edge added, False if already exists
        """
        # Add vertices if they don't exist
        if vertex1 not in self.adjacency_list:
            self.add_vertex(vertex1)
        if vertex2 not in self.adjacency_list:
            self.add_vertex(vertex2)

        # Check if edge already exists
        if vertex2 in self.adjacency_list[vertex1]:
            print(f"[Warning] Edge {vertex1} -- {vertex2} already exists")
            return False

        # Add edge (undirected)
        self.adjacency_list[vertex1].append(vertex2)
        self.adjacency_list[vertex2].append(vertex1)
        self.num_edges += 1
        print(f"[Added Edge] {vertex1} -- {vertex2}")
        return True

    def remove_edge(self, vertex1, vertex2):
        """
        Remove an edge between two vertices.

        Args:
            vertex1: First vertex
            vertex2: Second vertex

        Returns:
            bool: True if removed, False if not found
        """
        if vertex1 not in self.adjacency_list or vertex2 not in self.adjacency_list:
            print(f"[Error] One or both vertices not found")
            return False

        if vertex2 in self.adjacency_list[vertex1]:
            self.adjacency_list[vertex1].remove(vertex2)
            self.adjacency_list[vertex2].remove(vertex1)
            self.num_edges -= 1
            print(f"[Removed Edge] {vertex1} -- {vertex2}")
            return True
        else:
            print(f"[Warning] Edge {vertex1} -- {vertex2} not found")
            return False

    def remove_vertex(self, vertex):
        """
        Remove a vertex and all its edges.

        Args:
            vertex: Vertex to remove

        Returns:
            bool: True if removed, False if not found
        """
        if vertex not in self.adjacency_list:
            print(f"[Error] Vertex {vertex} not found")
            return False

        # Remove all edges to this vertex
        for neighbor in self.adjacency_list[vertex]:
            self.adjacency_list[neighbor].remove(vertex)
            self.num_edges -= 1

        # Remove the vertex
        del self.adjacency_list[vertex]
        self.num_vertices -= 1
        print(f"[Removed Vertex] {vertex}")
        return True

    def get_neighbors(self, vertex):
        """
        Get all neighbors of a vertex.

        Args:
            vertex: Vertex to query

        Returns:
            list: List of neighbors, or empty list if vertex not found
        """
        return self.adjacency_list.get(vertex, [])

    def get_degree(self, vertex):
        """
        Get the degree of a vertex (number of edges connected to it).

        Args:
            vertex: Vertex to query

        Returns:
            int: Degree of the vertex
        """
        return len(self.adjacency_list.get(vertex, []))

    def display(self):
        """
        Display the graph in adjacency list format.
        Shows all vertices and their connected neighbors.
        """
        print("\n" + "="*60)
        print("GRAPH - ADJACENCY LIST REPRESENTATION")
        print("="*60)

        if self.num_vertices == 0:
            print("Graph is empty")
            return

        # Sort vertices for consistent display
        for vertex in sorted(self.adjacency_list.keys()):
            neighbors = sorted(self.adjacency_list[vertex])
            degree = len(neighbors)
            if neighbors:
                print(f"{vertex} -> {neighbors} (degree: {degree})")
            else:
                print(f"{vertex} -> [No neighbors] (degree: {degree})")

        print(f"\nStatistics:")
        print(f"  Total vertices: {self.num_vertices}")
        print(f"  Total edges: {self.num_edges}")

    def display_visual(self):
        """
        Display a simple visual representation of the graph.
        """
        if self.num_vertices == 0:
            print("Graph is empty")
            return

        print("\n" + "="*60)
        print("GRAPH VISUAL REPRESENTATION")
        print("="*60)

        for vertex in sorted(self.adjacency_list.keys()):
            neighbors = sorted(self.adjacency_list[vertex])
            if neighbors:
                for neighbor in neighbors:
                    if vertex < neighbor:  # Print each edge once
                        print(f"  {vertex} --- {neighbor}")

    def has_vertex(self, vertex):
        """
        Check if a vertex exists in the graph.

        Args:
            vertex: Vertex to check

        Returns:
            bool: True if exists, False otherwise
        """
        return vertex in self.adjacency_list

    def has_edge(self, vertex1, vertex2):
        """
        Check if an edge exists between two vertices.

        Args:
            vertex1: First vertex
            vertex2: Second vertex

        Returns:
            bool: True if edge exists, False otherwise
        """
        if vertex1 not in self.adjacency_list or vertex2 not in self.adjacency_list:
            return False
        return vertex2 in self.adjacency_list[vertex1]

    def dfs(self, start):
        """
        Perform Depth-First Search traversal.

        Args:
            start: Starting vertex

        Returns:
            list: Order of visited vertices
        """
        if start not in self.adjacency_list:
            print(f"[Error] Vertex {start} not found")
            return []

        visited = set()
        traversal_order = []

        self._dfs_recursive(start, visited, traversal_order)
        return traversal_order

    def _dfs_recursive(self, vertex, visited, traversal_order):
        """
        Recursive helper for DFS.
        """
        visited.add(vertex)
        traversal_order.append(vertex)

        for neighbor in sorted(self.adjacency_list[vertex]):
            if neighbor not in visited:
                self._dfs_recursive(neighbor, visited, traversal_order)

    def bfs(self, start):
        """
        Perform Breadth-First Search traversal.

        Args:
            start: Starting vertex

        Returns:
            list: Order of visited vertices
        """
        if start not in self.adjacency_list:
            print(f"[Error] Vertex {start} not found")
            return []

        from collections import deque

        visited = set([start])
        queue = deque([start])
        traversal_order = [start]

        while queue:
            vertex = queue.popleft()

            for neighbor in sorted(self.adjacency_list[vertex]):
                if neighbor not in visited:
                    visited.add(neighbor)
                    queue.append(neighbor)
                    traversal_order.append(neighbor)

        return traversal_order


def main():
    """
    Main function to demonstrate graph operations.
    Provides an interactive menu for user interaction.
    """
    print("\n" + "="*60)
    print("GRAPH REPRESENTATION - ADJACENCY LIST IMPLEMENTATION")
    print("="*60)
    print("Undirected graph with customizable vertices")
    print()

    graph = Graph()

    # Pre-populate with sample data
    sample_edges = [
        ("A", "B"),
        ("A", "C"),
        ("B", "D"),
        ("C", "D"),
        ("D", "E"),

    ]

    print("Creating sample graph...")
    for v1, v2 in sample_edges:
        graph.add_edge(v1, v2)

    graph.display()

    print("\nDFS traversal starting from A:")
    print(f"  {graph.dfs('A')}")

    print("\nBFS traversal starting from A:")
    print(f"  {graph.bfs('A')}")

    # Interactive menu
    while True:
        print("\n" + "-"*40)
        print("GRAPH OPERATIONS MENU")
        print("-"*40)
        print("1. Add vertex")
        print("2. Add edge")
        print("3. Remove vertex")
        print("4. Remove edge")
        print("5. Display graph (adjacency list)")
        print("6. Display visual representation")
        print("7. Check if vertex exists")
        print("8. Check if edge exists")
        print("9. Get vertex degree")
        print("10. DFS traversal")
        print("11. BFS traversal")
        print("12. Exit")

        try:
            choice = input("\nEnter your choice (1-12): ").strip()

            if choice == '1':
                vertex = input("Enter vertex name/label: ").strip()
                graph.add_vertex(vertex)
                graph.display()

            elif choice == '2':
                v1 = input("Enter first vertex: ").strip()
                v2 = input("Enter second vertex: ").strip()
                graph.add_edge(v1, v2)
                graph.display()

            elif choice == '3':
                vertex = input("Enter vertex to remove: ").strip()
                graph.remove_vertex(vertex)
                graph.display()

            elif choice == '4':
                v1 = input("Enter first vertex: ").strip()
                v2 = input("Enter second vertex: ").strip()
                graph.remove_edge(v1, v2)
                graph.display()

            elif choice == '5':
                graph.display()

            elif choice == '6':
                graph.display_visual()

            elif choice == '7':
                vertex = input("Enter vertex to check: ").strip()
                if graph.has_vertex(vertex):
                    print(f"Vertex '{vertex}' exists in the graph")
                else:
                    print(f"Vertex '{vertex}' does not exist in the graph")

            elif choice == '8':
                v1 = input("Enter first vertex: ").strip()
                v2 = input("Enter second vertex: ").strip()
                if graph.has_edge(v1, v2):
                    print(f"Edge {v1} -- {v2} exists")
                else:
                    print(f"Edge {v1} -- {v2} does not exist")

            elif choice == '9':
                vertex = input("Enter vertex: ").strip()
                degree = graph.get_degree(vertex)
                if degree >= 0:
                    print(f"Degree of vertex '{vertex}': {degree}")
                else:
                    print(f"Vertex '{vertex}' not found")

            elif choice == '10':
                start = input("Enter starting vertex: ").strip()
                result = graph.dfs(start)
                if result:
                    print(f"DFS traversal: {result}")

            elif choice == '11':
                start = input("Enter starting vertex: ").strip()
                result = graph.bfs(start)
                if result:
                    print(f"BFS traversal: {result}")

            elif choice == '12':
                print("\nExiting program. Goodbye!")
                break

            else:
                print("\nInvalid choice. Please enter a number between 1 and 12.")

        except KeyboardInterrupt:
            print("\n\nProgram interrupted by user. Exiting...")
            break


if __name__ == "__main__":
    main()